// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=tests/mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	contract "architecture-bricks/contract"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ApproveProduct mocks base method.
func (m *MockRepository) ApproveProduct(ctx context.Context, productID, moderatorID string, version int, event contract.ProductHistoryRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveProduct", ctx, productID, moderatorID, version, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveProduct indicates an expected call of ApproveProduct.
func (mr *MockRepositoryMockRecorder) ApproveProduct(ctx, productID, moderatorID, version, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveProduct", reflect.TypeOf((*MockRepository)(nil).ApproveProduct), ctx, productID, moderatorID, version, event)
}

// CreateProduct mocks base method.
func (m *MockRepository) CreateProduct(ctx context.Context, product contract.Product, events ...contract.ProductHistoryRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, product}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProduct", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockRepositoryMockRecorder) CreateProduct(ctx, product any, events ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, product}, events...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockRepository)(nil).CreateProduct), varargs...)
}

// GetProduct mocks base method.
func (m *MockRepository) GetProduct(ctx context.Context, productID string) (contract.Product, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, productID)
	ret0, _ := ret[0].(contract.Product)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockRepositoryMockRecorder) GetProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockRepository)(nil).GetProduct), ctx, productID)
}

// ProductHistory mocks base method.
func (m *MockRepository) ProductHistory(ctx context.Context, productID string) ([]contract.ProductHistoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProductHistory", ctx, productID)
	ret0, _ := ret[0].([]contract.ProductHistoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProductHistory indicates an expected call of ProductHistory.
func (mr *MockRepositoryMockRecorder) ProductHistory(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProductHistory", reflect.TypeOf((*MockRepository)(nil).ProductHistory), ctx, productID)
}

// RejectProduct mocks base method.
func (m *MockRepository) RejectProduct(ctx context.Context, productID, moderatorID string, version int, event contract.ProductHistoryRow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectProduct", ctx, productID, moderatorID, version, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectProduct indicates an expected call of RejectProduct.
func (mr *MockRepositoryMockRecorder) RejectProduct(ctx, productID, moderatorID, version, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectProduct", reflect.TypeOf((*MockRepository)(nil).RejectProduct), ctx, productID, moderatorID, version, event)
}

// UpdateProduct mocks base method.
func (m *MockRepository) UpdateProduct(ctx context.Context, product contract.Product, version int, events ...contract.ProductHistoryRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, product, version}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProduct", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockRepositoryMockRecorder) UpdateProduct(ctx, product, version any, events ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, product, version}, events...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockRepository)(nil).UpdateProduct), varargs...)
}
